# Generated by Django 3.2.4 on 2021-07-30 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('baseuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_main.baseuser')),
                ('profile_pic', models.ImageField(blank=True, default='profile.jpg', null=True, upload_to='profile')),
                ('bio', models.TextField(blank=True, null=True)),
                ('online_status', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('app_main.baseuser',),
        ),
    ]
