# Generated by Django 3.2.4 on 2021-07-30 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0001_initial'),
        ('app_chats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='members',
            field=models.ManyToManyField(to='app_accounts.Customers'),
        ),
    ]
