# Generated by Django 3.2.4 on 2021-07-30 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_chats', '0002_room_members'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='room_icon',
            new_name='icon',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='room_name',
            new_name='name',
        ),
    ]
